@startuml

'left to right direction
top to bottom direction

title Stand Diagram

class Vehicle {
vehicleID [pk]
vehicleName
vehicleLicensePlate
vehicleNumberSeats
vehicleNumberDoors
vehicleTraction
vehicleFuel
vehicleColor
vehicleStatus
vehicleType
clientId[fk]
modelID[fk]
buyerID
transactionID
}

class Client {
clientID[pk]
clientName
clientAddress
clientPhoneNumber
clientNif
clientEmailAddress
standID[fk]
}

class Stand {
standID[pk]
standName
standAddress
standPhoneNumber
standNif
standEmailAddress
}

class Brand {
brandId [pk]
brandName
}


class Model {
modelId [pk]
modelName
}

class Buyer  {
buyerId [pk]
buyerName
buyerAddress
buyerPhoneNumber
buyerNif
buyerEmailAddress
}

class Transaction   {
transactionID
transactionDate
sellingPrice
buyerId [fk]
}



Stand "1 " --down "       *"Vehicle : has >
Client "1" --down "         *"Vehicle : provides >
Stand "1" --down "*"Client : has >
Model "1    " --down "*"Vehicle : has >
Brand "1" --down "       *"Model : has >
Buyer "1" --down "       *"Vehicle : buys >
Buyer "1" --down "       1"Transaction : has >
Transaction "1" --down "     1"Vehicle : has >


@enduml