package com.example.stand.enums;

public enum Type {
    SEDAN, SUV, HATCHBACK, COUPE, CONVERTIBLE, MINIVAN, TRUCK, VAN, MOTORCYCLE, ELETRIC_VEHICLE, HYBRID_VEHICLE_CROSSOVER, LIMOUSINE, PICKUP_TRUCK
}
